# Generated by Django 5.2 on 2025-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_chakorufamily_francisfamily_kochuvareedfamily_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aipufamily',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='chakorufamily',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='francisfamily',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='kochuvareedfamily',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lonappanfamily',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='thomafamily',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='varunnyfamily',
            name='gender',
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aipufamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='burial_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='communion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='communion_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='employed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='marriage_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='membership_category',
            field=models.CharField(choices=[('LM', 'Life Member'), ('PM', 'Paid Member'), ('NM', 'Non Member')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Auto-generated with category prefix', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
