# Generated by Django 5.2 on 2025-06-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_aipufamily_gender_chakorufamily_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aipufamily',
            name='spouses',
        ),
        migrations.RemoveField(
            model_name='chakorufamily',
            name='spouses',
        ),
        migrations.RemoveField(
            model_name='francisfamily',
            name='spouses',
        ),
        migrations.RemoveField(
            model_name='kochuvareedfamily',
            name='spouses',
        ),
        migrations.RemoveField(
            model_name='lonappanfamily',
            name='spouses',
        ),
        migrations.RemoveField(
            model_name='thomafamily',
            name='spouses',
        ),
        migrations.RemoveField(
            model_name='varunnyfamily',
            name='spouses',
        ),
    ]
