# Generated by Django 5.2 on 2025-06-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_remove_aipufamily_spouses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipufamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.aipufamily'),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.chakorufamily'),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.francisfamily'),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.kochuvareedfamily'),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.lonappanfamily'),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.thomafamily'),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='family.varunnyfamily'),
        ),
    ]
