# Generated by Django 5.2 on 2025-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_aipufamily_spouses_chakorufamily_spouses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipufamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family-photo/'),
        ),
    ]
