# Generated by Django 5.2 on 2025-04-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Default Headline', max_length=255)),
                ('subhead', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/%y')),
            ],
        ),
    ]
