# Generated by Django 5.2 on 2025-04-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Default Headline', max_length=255)),
                ('subhead', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='events/%Y/%m/')),
                ('date', models.DateField()),
                ('category', models.CharField(default='Gatherings', max_length=100)),
            ],
        ),
    ]
