# Generated by Django 5.2 on 2025-05-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_profile_address_remove_profile_pin_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
