# Generated by Django 5.2 on 2025-05-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_member_address_member_baptisam_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='baptisam_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='baptisam_place',
        ),
        migrations.RemoveField(
            model_name='member',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='burial_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='burial_place',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cause_of_death',
        ),
        migrations.RemoveField(
            model_name='member',
            name='communion_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='communion_place',
        ),
        migrations.RemoveField(
            model_name='member',
            name='education',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='employed',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marriage_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marriage_place',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mobile_numbers',
        ),
        migrations.RemoveField(
            model_name='member',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='place_of_death',
        ),
    ]
