# Generated by Django 5.2 on 2025-05-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_discussionmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionMessage',
        ),
    ]
