# Generated by Django 5.2 on 2025-05-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_discussionmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='father',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouses',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
