# Generated by Django 5.2 on 2025-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_delete_comment_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('image', models.ImageField(upload_to='memory_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
