# Generated by Django 5.2 on 2025-05-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_topic_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
