# Generated by Django 5.2 on 2025-05-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
