# Generated by Django 5.2 on 2025-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='premium_events/')),
                ('description', models.TextField()),
            ],
        ),
    ]
