# Generated by Django 5.2 on 2025-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_premiumeventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumeventimage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumeventimage',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
