# Generated by Django 5.2 on 2025-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_premiumeventimage_date_premiumeventimage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumeventimage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='premiumeventimage',
            name='location',
        ),
        migrations.AddField(
            model_name='premiumevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumevent',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
