# Generated by Django 5.2 on 2025-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_premiumeventimage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_women_association',
            field=models.BooleanField(default=False),
        ),
    ]
